services:

  attachment-api:
    build:
      dockerfile: ./Dockerfile
    container_name: attachment-api
    scale: 0
    ports:
      - 3000:3000
    depends_on:
      postgres-attachment-api:
        condition: service_healthy
    command: /bin/sh -c "npx knex --env production migrate:latest && npm start"
    environment:
      - LOG_LEVEL=debug
      - DB_HOST=postgres-attachment-api
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sqnc-attachment-api
      - IPFS_HOST=ipfs
      - IDENTITY_SERVICE_HOST=identity-service
      - IDP_CLIENT_ID=sequence
      - IDP_PUBLIC_ORIGIN=http://localhost:3080
      - IDP_INTERNAL_ORIGIN=http://keycloak:8080
      - IDP_OAUTH2_REALM=sequence
      - IDP_INTERNAL_REALM=internal

  postgres-attachment-api:
    image: postgres:17.4-alpine
    container_name: postgres-attachment-api
    ports:
      - 5432:5432
    volumes:
      - attachment-api-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sqnc-attachment-api
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-identity-service:
    image: postgres:17.4-alpine
    container_name: postgres-identity
    ports:
      - 5433:5432
    volumes:
      - identity-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sqnc-identity-service
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  sqnc-identity-service:
    image: digicatapult/sqnc-identity-service:v4.0.4
    container_name: identity-service
    depends_on:
      postgres-identity-service:
        condition: service_healthy
    command: /bin/sh -c "npm run db:migrate && npm start"
    ports:
      - 3002:3000
    environment:
      - API_HOST=sqnc-node
      - DB_HOST=postgres-identity-service
      - DB_PORT=5432
      - DB_NAME=sqnc-identity-service
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SELF_ADDRESS=5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
      - IDP_CLIENT_ID=sequence
      - IDP_PUBLIC_ORIGIN=http://localhost:3080
      - IDP_INTERNAL_ORIGIN=http://keycloak:8080
      - IDP_OAUTH2_REALM=sequence
      - IDP_INTERNAL_REALM=internal

  sqnc-node:
    image: digicatapult/sqnc-node:v12.3.0
    container_name: node
    command: --base-path /data/ --dev --unsafe-rpc-external --rpc-max-connections 512 --rpc-cors all
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    restart: on-failure

  ipfs:
    image: ipfs/go-ipfs:v0.34.1
    container_name: ipfs
    environment:
      - |
        IPFS_SWARM_KEY=/key/swarm/psk/1.0.0/
        /base16/
        0000000000000000000000000000000000000000000000000000000000000000
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 3080:8080
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm

volumes:
  attachment-api-storage:
  identity-storage:
