services:
  postgres-attachment-api:
    image: postgres:17.5-alpine
    container_name: postgres-attachment-api
    ports:
      - 5432:5432
    volumes:
      - attachment-api-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sqnc-attachment-api

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 3080:8080
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm
  minio:
    image: bitnami/minio:latest
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566' # main API
    environment:
      - SERVICES=s3
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=eu-west-2
    volumes:
      - localstack_data:/var/lib/localstack
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - 10000:10000
    volumes:
      - ./azurite-data:/data
      - ./azurite-logs:/logs
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000 --location /data --debug /logs/debug.log

volumes:
  attachment-api-storage:
  localstack_data:
